### ISSUE TITLE
Paramétros de longitud y latitud incorrectos

### ISSUE THREAD

**Issue by davidsl83** [DelgadoPanadero/CatastRo#1]
En la definición de la función getRC(lat, lon, SRS) tenemos que lat corresponde a la latitud y lon a la longitud. Sin embargo si nos vamos al ejemplo 
direction <- getRC(lat = -3.45624183836806, lon = 38.6196566583596)
print(direction) 

Nos da como resultado
$address
[1] "DS DISEMINADO  Polígono 18 Parcela 39  EL TIRADERO. SANTA CRUZ DE MUDELA (CIUDAD REAL)"
$RC
[1] "000100200VH67C"

En realidad para esta ubicación la longitud es -3.45624183836806 y la latitud es 38.6196566583596; con lo que podemos indicar que en la función se está llamando a los parámetros de longitud y latitud de forma errónea, debería de cambiarse latitud por longitud y viceversa.

**Comment by DelgadoPanadero** [comment]
Resuelto
