### ISSUE TITLE
Creo que estoy haciendo algo mal

### ISSUE THREAD

**Issue by hdnh2006** [DelgadoPanadero/CatastRo#2]
Hola, he intentado dos direcciones:

Paseo Delicias 81, Madrid usando: getRC(lat=40.4283916, lon=-3.6836671999999453).
Calle Velazquez 64, Madrid usando: getRC(lat=40.39679659999999, lon=-3.6939078999999992).

El mensaje que recibo en ambas es “Error in getRC(lat,lon) : NO EXISTE ESE REGISTRO”

**Comment by DelgadoPanadero** [comment]
Es por el sistema de coordenadas que estás usando, WGS 80, por defecto getR() usa las coordenadas ED50. Para cambiar al sistema de coordenadas que quieres, tienes que pasarle a la función el argumento SRS = "EPSG:4326"
